### PR TITLE
Issue/141/create postage stamps

### PR DESCRIPTION
**Pull request by jchiang87**
#141:

Here is the first version.  We need to decide how to display things in a notebook.  The example code uses ds9, but presumably we'd want to use matplotlib.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Let's use matplotlib since it is the prevailiing community standard - example code here:

https://github.com/drphilmarshall/StatisticalMethods/blob/master/examples/XrayImage/FirstLook.ipynb

**Comment by drphilmarshall** [comment]
Notes from conversation:

* Let's start a `Display` module with a static function for using matpotlib to show FITS images. This can also be where we make light curve plots, eh @rbiswas4 ? And also color composite creation ( @SimonKrughoff )
* Enable array inputs (and hence array outputs): sometimes we'll want all stamps at one ra,dec from N exposures, and other times we'll want all stamps from one exposure at N ra,dec positions...
* Display methods will also need to handle array inputs (and outputs)

**Comment by drphilmarshall** [comment]
Also:

* [ ] Check in small FITS image
* [ ] Check in tests

**Comment by rbiswas4** [comment]
> Let's start a Display module with a static function for using matpotlib to show FITS images. This can also be where we make light curve plots, eh @rbiswas4 

Sounds good to me: Of course, this will import and heavily depend on @jbkalmbach's project where we are assembling the truth information.

**Comment by jchiang87** [comment]
I added a`Display` module, test code, array generation, etc..  I think this is ready to consider merging into master.  Please have a look.

**Comment by drphilmarshall** [comment]
This looks good to me, Jim! The notebook is great. I guess this will break the reorg pull request #147 - we'd better merge into the reorganize branch and consider merging that PR soon, too...

**Comment by jchiang87** [comment]
@drphilmarshall Is that the usual way of handling these things?  I was thinking we could just merge this into master and then deal with conflicts over at #147 when it's time to merge that PR (which I agree we should do right away).  Otherwise the work in this branch may get held up in the reorganize branch if there are other issues to deal with there.

**Comment by drphilmarshall** [comment]
I think you are saying exactly what I was trying to say, but better :-) Merging this PR (#149) now!

**Pull request merged**
