### PR TITLE
futurize code for Python 3 compatibility

### PR DESCRIPTION
**Pull request by jchiang87**
This addresses #209.   

Developers should push their futurized code and any other related files to this branch.  Comments on the changes can take place here.

Once this branch builds cleanly in travis, we can merge.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Uh-oh - no cigar!

**Comment by jchiang87** [comment]
I only updated code that I personally wrote.  As @rbiswas4 suggested back at #209, I was hoping everyone else would follow suit with the code they contributed.

**Comment by rbiswas4** [comment]
Yes, I mean to follow suit by tomorrow's meeting ....

Rahul

**Comment by jchiang87** [comment]
I've made modest changes to `bin/colorim.py`, `python/desc/twinkles/[generatePhosimInput.py,sprinkler.py,validate.py]` and omitted the `workflows` folder from the `pylint --py3k` checks, so everything passes.  @drphilmarshall @rbiswas4 I'd like to merge this if there are no objections.

**Comment by rbiswas4** [comment]
I think it would be great to merge this! Should we add a second pylint statement to check our code in python 2.7 ? That should be a separate issue.

**Comment by jchiang87** [comment]
yes, I'd be in favor of a set of pylint 2.7 checks.  I'll create the issue.

**Comment by jchiang87** [comment]
fixes #209

**Pull request merged**
