### PR TITLE
update bin/plot_point_mags.py to do multibands

### PR DESCRIPTION
**Pull request by jchiang87**
This supersedes `bin/plot_point_mags_gri.py`.  This operates on an output data repository without having to specify the bands or visits as it finds them from the registry.sqlite3 file:
```
$ plot_point_mags.py --help
usage: plot_point_mags.py [-h] [--skip_fit] data_repo outfile

For an output repository of Level 2 data, make a plot of stdev vs median flux
of forced sources.

positional arguments:
  data_repo   Output repository for Level 2 analysis
  outfile     Filename of the output png file

optional arguments:
  -h, --help  show this help message and exit
  --skip_fit  Skip the fitting of the snr curve
```

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Sorry for the delay, @jchiang87 - who should review this code? @SimonKrughoff ?

**Comment by jchiang87** [comment]
Sure, Simon would be the right person.  I'm wondering if this sort of script isn't superseded by the `validate_drp` stuff at #167.  Also, since this file gets the data from the forced source FITS catalogs, it doesn't scale very well for large processing runs.   It might make more sense to have it do db queries instead (assuming we get that going as a regular feature of the pipeline output).

**Comment by drphilmarshall** [comment]
Yeah - but we should merge this first and then deal with the db upgrade later. I made a note in #167 for @wmwv to think about.

**Comment by SimonKrughoff** [comment]
All these changes look very good improvements on the original.  Thanks for the excellent improvements @jchiang87 .  I assume I should leave it to you to deal with the merge conflicts merge and close, but I'm open to revising that process.

**Pull request merged**
