### PR TITLE
U/danielsf/mangle galtileid

### PR DESCRIPTION
**Pull request by danielsf**
this PR should solve the problem of AGN object IDs getting misrepresented in PhoSim

### CODE REVIEW

**Comment by jbkalmbach** [comment]
Did you do a check to confirm unique Ids in the Twinkles area?

**Comment by danielsf** [comment]
I generated one InstanceCatalog and verified that

1) the uniqueIDs were all less than 10^16
2) the IDs were unique

but just for one InstanceCatalog

**Comment by danielsf** [comment]
Actually... I tested "a pointing".  It wasn't actually the Twinkles field

**Comment by danielsf** [comment]
I am generating a Twinkles field now

**Comment by danielsf** [comment]
The actual Twinkles field also passes the test.  The largest IDs are now the supernova IDs, which, by definition, can't go higher than 7*10^15

**Comment by jbkalmbach** [comment]
Looks good. I've confirmed the Lensed AGN systems id numbers still contain all the correct information and there are the same number of them.

**Comment by danielsf** [comment]
@jbkalmbach It looks like I am not authorized to push to this repo.  You will have to merge the PR for me.

**Comment by jbkalmbach** [comment]
@danielsf Looks like I can't either actually. @jchiang87 @drphilmarshall Can one of you help us?

**Comment by jchiang87** [comment]
I don't have authorization either.   @drphilmarshall help!

**Comment by danielsf** [comment]
At least we don't have to worry about accidentally force-pushing to master....

**Comment by drphilmarshall** [comment]
Wow. I feel like I have too much power, here. I'll take a look at the settings. Thanks for the bugfix, Scott! :-)

**Comment by drphilmarshall** [comment]
OK, FYI: I removed the restriction on who can push to master (it was set to be only the DESC admins, by default), and replaced it with the requirement that a review "Approval" must be given instead. I think this makes more sense for us.

**Comment by rbiswas4** [comment]
This also closes: https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/312 which is specific to run 3, since we are not going to be able to do much else. However, we should keep track of this issue for a more graceful solution in future maybe.

**Pull request merged**
