### PR TITLE
turn on cosmic ray repair

### PR DESCRIPTION
**Pull request by jchiang87**
This addresses #322 

@SimonKrughoff : Is this all we need to turn on to handle cosmic rays?  What about `charImage.repair.doInterpolate`?  Is that relevant for this?

@tony-johnson

### CODE REVIEW

**Comment by SimonKrughoff** [comment]
@jchiang87 `charImage.repair.doInterpolate` should definitely be turned on (set to `True`).  Most of the downstream code assumes the cosmic rays are not just detected but interpolated.

**Comment by jchiang87** [comment]
Ok. I'll turn that on, but I note that when I ran `processEimage.py` with `--config charImage.repair.doCosmicRay=True` on the data for v222588-fu, the resulting S11.fits files were identical, with and without the `doInterpolate` flag set.  BTW, that's one of the visits where the the CR repair failed with `cosmicray.nCrPixelMax` left at its default value of 10000.

**Comment by jchiang87** [comment]
Thanks, @SimonKrughoff .  @drphilmarshall Can you merge when ready please?

**Comment by drphilmarshall** [comment]
Travis timed out again - not sure what we can do about that. Thanks Jim, thanks Simon!

**Comment by jchiang87** [comment]
This closes #322, and closes #297 , as well.

**Pull request merged**
