### PR TITLE
U/danielsf/cache galaxies

### PR DESCRIPTION
**Pull request by danielsf**
This should address issue #346 

When users run generatePhoSimInput.py, the code checks for a sqlite database $TWINKLES_DIR/data/galaxy_cache.db, containing all of the galaxies in the Twinkles field of view.  If this database is not there, the code creates it.  This local database is then used to generate the galaxies in the PhoSim InstanceCatalogs.

### CODE REVIEW

**Comment by jbkalmbach** [comment]
This looks good to me. I'm not going to request that this be done before merging this, but I'm making a new issue where we update the repo [setup instructions](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Setup.md) because I didn't notice before, but it looks like we have removed "generatePhosimInput.py" from our pipeline and moved it into twinkles_sky?

**Comment by jchiang87** [comment]
@rbiswas4 @jbkalmbach Are you guys ok with these changes?  If so, I think we should go ahead and merge.

**Comment by jbkalmbach** [comment]
@jchiang87 @danielsf Yeah unless Rahul has any objections let's merge it.

**Comment by rbiswas4** [comment]
Only one comment: 
Are we changing the units in which the ra, dec are stored obtained ? It used to be in radians
but the class GalaxyTileObjDegrees(GalaxyTileObj) suggests that it is in degrees?  More generally, it might be good to add a docstring with the units. 

Otherwise this is good to merge.

**Comment by danielsf** [comment]
CatSim expects ra, dec to be stored externally (i.e. on fatboy) in degrees.  Because GalaxyTileObjDegrees exists solely to produce a stand-in for fatboy, it needs to output ra, dec in degrees.

**Comment by rbiswas4** [comment]
Ah ... so the classes will work in the same way. OK got it!

**Pull request merged**
